[workspace]
members = [
    "did-core",
    "did-helpers",
    "did-iota",
    "examples"
 ]
exclude = [
    "libraries/c",
    "libraries/go",
    "libraries/java",
    "libraries/python",
    "libraries/wasm",
]